from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, Field
from database.models import DocumentChunk
from database.config import get_db
from backend.services.core_ai_qa_service import generate_answer_with_citations
from fastapi.security import OAuth2PasswordBearer

router = APIRouter(tags=["Core AI / Q&A"])

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="api/auth/login")

class QueryRequest(BaseModel):
    query: str = Field(..., title="User Query", description="The query to be answered by the AI model.")

class ChunkCitation(BaseModel):
    chunk_index: int = Field(..., title="Chunk Index", description="Index of the chunk in the document.")
    content: str = Field(..., title="Chunk Content", description="Content of the chunk.")
    metadata: dict = Field(..., title="Chunk Metadata", description="Metadata associated with the chunk.")

class QueryResponse(BaseModel):
    answer: str = Field(..., title="Generated Answer", description="The answer generated by the AI model.")
    citations: List[ChunkCitation] = Field(..., title="Citations", description="List of chunks used as citations.")

@router.post("/query", response_model=QueryResponse, status_code=status.HTTP_200_OK)
async def ai_query(
    query_request: QueryRequest,
    db: Session = Depends(get_db),
    token: str = Depends(oauth2_scheme)
):
    """
    Endpoint to handle AI queries. Retrieves the top-5 relevant chunks and generates an answer with citations.
    """
    try:
        # Extract query from request
        query = query_request.query

        # Generate answer and citations using the AI service
        answer, citations = generate_answer_with_citations(query, db)

        # Format citations for response
        formatted_citations = [
            ChunkCitation(
                chunk_index=citation.chunk_index,
                content=citation.content,
                metadata=citation.metadata
            )
            for citation in citations
        ]

        return QueryResponse(answer=answer, citations=formatted_citations)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while processing the query: {str(e)}"
        )